---
- name: Apply Docker Role
  hosts: itso
  become: true
  roles:
    - docker

- name: Apply Jenkins Role
  hosts: itso
  become: true
  roles:
    - jenkins

- name: Apply MinIO Role
  hosts: itso
  become: true
  roles:
    - minio
