---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install SDKMAN
  shell: |
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
  become: true
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Install OpenJDK 17 using SDKMAN
  shell: |
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install java 17.0.13-zulu 
  become: true
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Add Jenkins GPG key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Open Jenkins port (8080)
  ufw:
    rule: allow
    port: 8080
    proto: tcp
    state: enabled
